/**
 * The canonical, deterministic `anvil.lock` writer + reader.
 *
 * The lock is the sole build input and the determinism spine: the same manifest
 * resolved under the same frozen clock must produce a **byte-identical** lock on
 * any OS and any Node version. We own the serialization end to end — fixed key
 * order, sorted packages, one string-escape table, forced `/` paths, plain
 * integers — so nothing about the host (locale, path sep, map iteration order,
 * a TOML library's formatting choices) can leak into the bytes.
 *
 * Reading is tolerant (parse via `smol-toml`, then reconstruct the typed
 * `Lockfile`); only *writing* must be canonical.
 */

import { parse as parseToml } from "smol-toml";
import { LockParseError } from "../types/errors.js";
import type {
  Hash,
  HashAlgo,
  ItemKind,
  LockMeta,
  LockPackage,
  Lockfile,
  Placement,
  Provenance,
  SourceKind,
} from "../types/index.js";
import { inlineTable, kv, tomlInt, tomlPath, tomlString } from "./toml.js";

const HEADER = "# anvil.lock — generated by lobbify-anvil. Do not edit by hand.";

const HASH_ALGOS: ReadonlySet<string> = new Set<HashAlgo>(["sha1", "sha256"]);
const PROVENANCES: ReadonlySet<string> = new Set<Provenance>(["copy", "replay"]);
const SOURCE_KINDS: ReadonlySet<string> = new Set<SourceKind>([
  "mojang",
  "modrinth",
  "curseforge",
  "url",
  "local",
]);
const ITEM_KINDS: ReadonlySet<string> = new Set<ItemKind>([
  "game",
  "loader",
  "library",
  "java",
  "mod",
  "resourcepack",
  "shaderpack",
  "datapack",
  "config",
]);

// --- hash <-> "algo:value" -------------------------------------------------

/** Render a hash as the compact, stable `"algo:value"` lock form. */
export function hashToString(hash: Hash): string {
  return `${hash.algo}:${hash.value}`;
}

function parseHash(raw: unknown, where: string): Hash {
  if (typeof raw !== "string") {
    throw new LockParseError(`${where}: expected a "algo:value" hash string`);
  }
  const idx = raw.indexOf(":");
  if (idx <= 0) {
    throw new LockParseError(`${where}: malformed hash "${raw}"`);
  }
  const algo = raw.slice(0, idx);
  const value = raw.slice(idx + 1);
  if (!HASH_ALGOS.has(algo)) {
    throw new LockParseError(`${where}: unknown hash algorithm "${algo}"`);
  }
  if (!/^[0-9a-f]+$/.test(value)) {
    throw new LockParseError(`${where}: hash value is not lowercase hex`);
  }
  return { algo: algo as HashAlgo, value };
}

// --- placement -------------------------------------------------------------

/** The canonical inline-table rendering of a placement (fixed key order). */
function renderPlacement(p: Placement): string {
  switch (p.method) {
    case "link":
      return inlineTable([
        ["method", tomlString("link")],
        ["target", tomlPath(p.target)],
      ]);
    case "extract":
      return inlineTable([
        ["method", tomlString("extract")],
        ["targetDir", tomlPath(p.targetDir)],
      ]);
    case "asset-tree":
      return inlineTable([
        ["method", tomlString("asset-tree")],
        ["indexTarget", tomlPath(p.indexTarget)],
      ]);
    case "store-only":
      return inlineTable([["method", tomlString("store-only")]]);
  }
}

function toPosix(value: string): string {
  return value.split("\\").join("/");
}

function parsePlacement(raw: unknown, where: string): Placement {
  if (typeof raw !== "object" || raw === null) {
    throw new LockParseError(`${where}: missing placement table`);
  }
  const t = raw as Record<string, unknown>;
  const method = t.method;
  switch (method) {
    case "link":
      return { method: "link", target: toPosix(String(t.target)) };
    case "extract":
      return { method: "extract", targetDir: toPosix(String(t.targetDir)) };
    case "asset-tree":
      return { method: "asset-tree", indexTarget: toPosix(String(t.indexTarget)) };
    case "store-only":
      return { method: "store-only" };
    default:
      throw new LockParseError(`${where}: unknown placement method "${String(method)}"`);
  }
}

// --- package ordering ------------------------------------------------------

/** A stable comparator so package order is independent of resolution order. */
export function comparePackages(a: LockPackage, b: LockPackage): number {
  return (
    a.name.localeCompare(b.name, "en") ||
    a.source.localeCompare(b.source, "en") ||
    a.kind.localeCompare(b.kind, "en") ||
    a.hash.value.localeCompare(b.hash.value, "en")
  );
}

// --- serialize -------------------------------------------------------------

function renderPackage(pkg: LockPackage): string {
  // Fixed key order — part of the canonical form. Optional fields are omitted
  // (not emitted as empty) so their presence is meaningful and stable.
  const lines: string[] = ["[[package]]"];
  lines.push(kv("name", tomlString(pkg.name)));
  lines.push(kv("source", tomlString(pkg.source)));
  lines.push(kv("kind", tomlString(pkg.kind)));
  if (pkg.version !== undefined) {
    lines.push(kv("version", tomlString(pkg.version)));
  }
  lines.push(kv("provenance", tomlString(pkg.provenance)));
  lines.push(kv("hash", tomlString(hashToString(pkg.hash))));
  if (pkg.size !== undefined) {
    lines.push(kv("size", tomlInt(pkg.size)));
  }
  if (pkg.url !== undefined) {
    lines.push(kv("url", tomlString(pkg.url)));
  }
  if (pkg.project !== undefined) {
    lines.push(kv("project", tomlInt(pkg.project)));
  }
  if (pkg.file !== undefined) {
    lines.push(kv("file", tomlInt(pkg.file)));
  }
  lines.push(kv("placement", renderPlacement(pkg.placement)));
  return lines.join("\n");
}

function renderMeta(meta: LockMeta): string {
  return [
    "[meta]",
    kv("minecraft", tomlString(meta.minecraft)),
    kv("loader", tomlString(meta.loader)),
    kv("java", tomlString(meta.java)),
    kv("manifest_hash", tomlString(hashToString(meta.manifestHash))),
  ].join("\n");
}

/** Serialize a lockfile to its canonical, byte-stable TOML form. */
export function serializeLock(lock: Lockfile): string {
  const packages = [...lock.resolved].sort(comparePackages);
  const blocks: string[] = [
    HEADER,
    kv("version", tomlInt(lock.meta.version)),
    "",
    renderMeta(lock.meta),
  ];
  for (const pkg of packages) {
    blocks.push("");
    blocks.push(renderPackage(pkg));
  }
  // Trailing newline — a canonical text file ends in exactly one `\n`.
  return `${blocks.join("\n")}\n`;
}

// --- parse -----------------------------------------------------------------

function asString(raw: unknown, where: string): string {
  if (typeof raw !== "string") {
    throw new LockParseError(`${where}: expected a string`);
  }
  return raw;
}

function asInt(raw: unknown): number | undefined {
  if (raw === undefined) {
    return undefined;
  }
  if (typeof raw === "bigint") {
    return Number(raw);
  }
  if (typeof raw === "number" && Number.isInteger(raw)) {
    return raw;
  }
  throw new LockParseError(`expected an integer, got ${typeof raw}`);
}

function parsePackage(raw: unknown, i: number): LockPackage {
  if (typeof raw !== "object" || raw === null) {
    throw new LockParseError(`package[${i}]: not a table`);
  }
  const t = raw as Record<string, unknown>;
  const where = `package[${i}]`;
  const source = asString(t.source, where);
  const kind = asString(t.kind, where);
  const provenance = asString(t.provenance, where);
  if (!SOURCE_KINDS.has(source)) {
    throw new LockParseError(`${where}: unknown source "${source}"`);
  }
  if (!ITEM_KINDS.has(kind)) {
    throw new LockParseError(`${where}: unknown kind "${kind}"`);
  }
  if (!PROVENANCES.has(provenance)) {
    throw new LockParseError(`${where}: unknown provenance "${provenance}"`);
  }
  const pkg: LockPackage = {
    name: asString(t.name, where),
    source: source as SourceKind,
    kind: kind as ItemKind,
    provenance: provenance as Provenance,
    hash: parseHash(t.hash, where),
    placement: parsePlacement(t.placement, where),
    ...(t.version !== undefined ? { version: asString(t.version, where) } : {}),
    ...(t.size !== undefined ? { size: asInt(t.size) } : {}),
    ...(t.url !== undefined ? { url: asString(t.url, where) } : {}),
    ...(t.project !== undefined ? { project: asInt(t.project) } : {}),
    ...(t.file !== undefined ? { file: asInt(t.file) } : {}),
  };
  return pkg;
}

/** Parse an `anvil.lock` back into a typed lockfile (tolerant reader). */
export function parseLock(text: string): Lockfile {
  let doc: Record<string, unknown>;
  try {
    doc = parseToml(text) as Record<string, unknown>;
  } catch (err) {
    throw new LockParseError(`could not parse lock: ${(err as Error).message}`);
  }
  const version = asInt(doc.version);
  if (version !== 1) {
    throw new LockParseError(`unsupported lock schema version ${String(version)}`);
  }
  const metaRaw = doc.meta;
  if (typeof metaRaw !== "object" || metaRaw === null) {
    throw new LockParseError("missing [meta] table");
  }
  const m = metaRaw as Record<string, unknown>;
  const meta: LockMeta = {
    version: 1,
    minecraft: asString(m.minecraft, "meta"),
    loader: asString(m.loader, "meta"),
    java: asString(m.java, "meta"),
    manifestHash: parseHash(m.manifest_hash, "meta"),
  };
  const pkgsRaw = doc.package;
  const list = Array.isArray(pkgsRaw) ? pkgsRaw : [];
  const resolved = list.map((p, i) => parsePackage(p, i));
  return { meta, resolved };
}
